"""initial schema: documents, chunks, conversations, messages, citations, state

Revision ID: c1e34196be86
Revises: 
Create Date: 2026-07-28 00:08:31.417730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1e34196be86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('blob_ref', sa.LargeBinary(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('sanitization_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_sha256', name='uq_documents_user_sha')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_index('ix_documents_user_status', 'documents', ['user_id', 'status'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('parent_text', sa.Text(), nullable=False),
    sa.Column('parent_char_start', sa.Integer(), nullable=False),
    sa.Column('parent_char_end', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=512), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(length=16), nullable=False),
    sa.Column('is_derived', sa.Boolean(), nullable=False),
    sa.Column('related_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'chunk_index', name='uq_chunks_doc_index')
    )
    op.create_index('ix_chunks_user_doc', 'chunks', ['user_id', 'doc_id'], unique=False)
    op.create_index(op.f('ix_chunks_user_id'), 'chunks', ['user_id'], unique=False)
    op.create_table('conversation_state',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('rolling_summary', sa.Text(), nullable=True),
    sa.Column('entity_ledger', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversation_state_user_id'), 'conversation_state', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('degradations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pipeline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('message_citations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('chunk_id', sa.String(length=24), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('marker', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('fused_score', sa.Float(), nullable=True),
    sa.Column('rerank_score', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_citations_message', 'message_citations', ['message_id', 'marker'], unique=False)
    op.create_index(op.f('ix_message_citations_user_id'), 'message_citations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_citations_user_id'), table_name='message_citations')
    op.drop_index('ix_citations_message', table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index('ix_messages_conv_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_state_user_id'), table_name='conversation_state')
    op.drop_table('conversation_state')
    op.drop_index(op.f('ix_chunks_user_id'), table_name='chunks')
    op.drop_index('ix_chunks_user_doc', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('user_preferences')
    op.drop_index('ix_documents_user_status', table_name='documents')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
