"""add workspaces, workspace_id on documents and conversations

Revision ID: decf4fc2169c
Revises: c1e34196be86
Create Date: 2026-07-28 16:43:42.047139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decf4fc2169c'
down_revision: Union[str, Sequence[str], None] = 'c1e34196be86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=False)
    op.add_column('conversations', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_conversations_workspace_id', 'conversations', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('uq_documents_user_sha'), 'documents', type_='unique')
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_unique_constraint('uq_documents_user_ws_sha', 'documents', ['user_id', 'workspace_id', 'content_sha256'])
    op.create_foreign_key('fk_documents_workspace_id', 'documents', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_workspace_id', 'documents', type_='foreignkey')
    op.drop_constraint('uq_documents_user_ws_sha', 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.create_unique_constraint(op.f('uq_documents_user_sha'), 'documents', ['user_id', 'content_sha256'], postgresql_nulls_not_distinct=False)
    op.drop_column('documents', 'workspace_id')
    op.drop_constraint('fk_conversations_workspace_id', 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_column('conversations', 'workspace_id')
    op.drop_index(op.f('ix_workspaces_user_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
